export const REQUEST_TODOS = "REQUEST_TODOS";
export const ADD_TODO = "ADD_TODO";

export const RECEIVE_DATA = "REQUEST_DATA_SUCESS";
export const CATCH_FAILURE = "REQUEST_DATA_FAILURE";
export const REQUEST_DATA = "REQUEST_DATA_STARTED";
